name: auto syu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: "0 22 * * *" # cron表达式，Actions时区是UTC时间，所以要往前推8个小时
jobs:
  sign_in:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade requests
        python -m pip install --upgrade pip
        pip install pyppeteer
        pyppeteer-install
    - name: 'Sign In'
      env:
          PARM: ${{ secrets.PARM }}
          WXTS: ${{ secrets.WXTS }} 
      run: |
          python3 yiqing.py
